ci: Fix downloading the latest release of Obelisk

diff --git a/.github/workflows/check-verify.yml b/.github/workflows/check-verify.yml
--- a/.github/workflows/check-verify.yml
+++ b/.github/workflows/check-verify.yml
@@ -41,9 +41,21 @@ jobs:
 
       - name: Download obelisk
         run: |
+          REPO="obeli-sk/obelisk"
           FILE="obelisk-x86_64-unknown-linux-gnu.tar.gz"
-          curl --fail -L -o "$FILE" \
-            https://github.com/obeli-sk/obelisk/releases/download/latest/$FILE
+
+          LATEST_TAG=$(curl -sI -L https://github.com/$REPO/releases/latest \
+              | grep -i "location:" \
+              | grep -oP 'tag/\K[^/]+' \
+              | sed 's/\r//')
+
+          if [ -z "$LATEST_TAG" ]; then
+            echo "Failed to determine the latest release tag!"
+            exit 1
+          fi
+
+          ARTIFACT_URL="https://github.com/$REPO/releases/download/$LATEST_TAG/$FILE"
+          curl --fail -L -o "$FILE" $ARTIFACT_URL
           tar xzfv "$FILE"
       - name: Verify obelisk-local.toml
         run: ./obelisk server verify --config obelisk-local.toml
